WIP: refactoring & documentation implementation
kestra-io/vscode-kestra pull request #12
Opened 2023-11-24 08:11 UTC by Skraye

2023-11-27 15:59 UTC, Skraye commented
@rldorado I've assign you if you want to take a look at what is our vs code extension and maybe you could give some advice!

2023-11-27 16:35 UTC, anna-geller commented on README.md
> +- Dynamic documentation depending on tasks your flow includes.
```suggestion
- Code autocompletion and syntax validation on `.yaml` and `.yml` flow files once you download Kestra's JSON schema.
- Dynamic documentation depending on tasks added to your flow.
```

2023-11-27 16:39 UTC, anna-geller commented on README.md
> +**Using the extension on the Kestra VSCode Kestra will automatically download the Schema.**
```suggestion
Note that when using the Kestra VS Code extension within Kestra's editor embedded in the UI, you don't need to download the schema — Kestra does it automatically.
```

2023-11-27 16:46 UTC, anna-geller commented on README.md
> +**If you have a JWT-based authentication (EE), please copy your token from the "Copy JWT token" button available in the same menu as the Logout button on the UI.**
```suggestion
### Enabling live documentation for Kestra plugins

Kestra VS Code extension embeds the plugin's documentation, showing live documentation for each task and trigger. When on a YAML file, a new action called `Open Kestra Documentation` will appear and open a new web view. This view contains:
1. The default properties of a flow and tasks
2. Task and trigger documentation — available once you click on a specific task or trigger within your code.

## Configure

When using the extension in your local VS Code IDE, you will be prompted to enter a URL. That URL is the default endpoint of the Kestra API, which includes all plugins. If you want to display only plugins available in your instance, use the URL of your Kestra Instance.

**If you have a JWT-based authentication (EE), make sure to copy your token from the "Copy JWT token" button available in the same menu as the Logout button in the UI.**
```

2023-11-27 18:02 UTC, anna-geller approved these changes

2023-11-28 09:40 UTC, Nico-Kestra commented
For me, the icon is okay since it's the same one used in the Help section for documentation.

2023-11-30 10:15 UTC, rldorado commented on src/web/documentation/documentation.ts
> +const kestraBaseUrl = "https://api.kestra.io/v1";
Minor thing, I'd would have used a constant to handle this url in a `constants.ts` file or something similar.

2023-11-30 10:17 UTC, rldorado commented on src/web/documentation/documentation.ts
> +let channel = vscode.window.createOutputChannel("Kestra - Docs");
Another minor thing, I think this is potentially to be encapsulated within DocumentationPanel class to avoid use of global state.

2023-11-30 10:23 UTC, rldorado commented on src/web/extension.ts
> +const kestraBaseUrl = "https://api.kestra.io/v1";
Again, you could avoid to duplicate const definitions of `kestraBaseUrl` everywhere from a `constants.ts` file module.

2023-11-30 10:30 UTC, brian-mulier-p requested changes
- Doesn't work on Kestra EE (we get a 401, get asked our credentials which lead to a 200 but then doc is still not displayed and we get asked our credentials everytime we move our cursor)
- Please reindent ts files
Ty and well done for the integration it's a smart and stylish idea :+1:

2023-11-30 10:30 UTC, brian-mulier-p commented on src/web/documentation/documentation.ts
> +    private readonly _kestraUrl: string;
This shouldn't be cached and always be retrieved through settings to prevent soft-locking users that miswrote their Kestra URL.

Moreover please always ask for Kestra URL in case of token expiration or failing to allow user to change it if they miswrote. You may prefill with the settings' one if there is one I think (or Kestra API as a fallback as done right now)

2023-11-30 11:36 UTC, rldorado commented
> @rldorado I've assign you if you want to take a look at what is our vs code extension and maybe you could give some advice!

Thank you for adding me and let me learn about VSCode extensions are working. I've just added some minor tweak comments.

2023-12-11 08:55 UTC, brian-mulier-p commented
I get a `2023-12-11 09:50:15,693 WARN  default-nioEventLoopGroup-1-31 io.kestra.webserver.access [Date: 2023-12-11T09:50:15.683714709+01:00] [Duration: 9 ms] [Method: GET] [Url: /api/v1/plugins/null] [Status: 404] [Length: 103] [Ip: 127.0.0.1] [Port: 8080]` call on every file change (on web only, standalone vscode seems not to do it)

2023-12-11 09:36 UTC, brian-mulier-p approved these changes
LGTM except this strange null call.

Note that the extension can't be used anymore for users with basic-auth enabled on their instance while we don't provide JWT or something.

2023-12-11 09:50 UTC, merged